FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npx prisma generate
RUN node --max-old-space-size=1024 node_modules/.bin/tsc \
    --outDir dist \
    --skipLibCheck \
    --esModuleInterop true \
    --module commonjs \
    --target es2017 \
    --moduleResolution node \
    --resolveJsonModule true \
    || true
CMD ["node", "--max-old-space-size=256", "dist/worker/index.js"]
