[build]
builder = "nixpacks"

[deploy]
startCommand = ""
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[[services]]
name = "web"
startCommand = "npx prisma generate && npm run build && npm start"
numReplicas = 1

[services.port]
port = 8080

[[services]]
name = "worker"
startCommand = "npm run build && npm run worker"
numReplicas = 1

[[services]]
name = "pusher"
startCommand = "npm run build && npm run pusher"
numReplicas = 1
